package com.cishi.beans;

import java.util.Date;

public class OrderTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.order_number
	 * @mbggenerated
	 */
	private String orderNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.last_update_date
	 * @mbggenerated
	 */
	private Date lastUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.last_update_userid
	 * @mbggenerated
	 */
	private String lastUpdateUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.order_name
	 * @mbggenerated
	 */
	private String orderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.launcher_id
	 * @mbggenerated
	 */
	private String launcherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.receiver_id
	 * @mbggenerated
	 */
	private String receiverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.info_obli_1
	 * @mbggenerated
	 */
	private String infoObli1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.info_obli_2
	 * @mbggenerated
	 */
	private String infoObli2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.info_obli_3
	 * @mbggenerated
	 */
	private String infoObli3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.info_obli_4
	 * @mbggenerated
	 */
	private String infoObli4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.introduce
	 * @mbggenerated
	 */
	private String introduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.type
	 * @mbggenerated
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.requirements
	 * @mbggenerated
	 */
	private String requirements;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.money
	 * @mbggenerated
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.order_receiver_id
	 * @mbggenerated
	 */
	private String orderReceiverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.end_time
	 * @mbggenerated
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.launcher_status
	 * @mbggenerated
	 */
	private Byte launcherStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.receiver_status
	 * @mbggenerated
	 */
	private Byte receiverStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.parent_id
	 * @mbggenerated
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.icon_id
	 * @mbggenerated
	 */
	private String iconId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.sort_num
	 * @mbggenerated
	 */
	private Integer sortNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_task.orinin_money
	 * @mbggenerated
	 */
	private Double orininMoney;
	
	private String att_id;
	
	public String getAtt_id() {
		return att_id;
	}

	public void setAtt_id(String att_id) {
		this.att_id = att_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.id
	 * @return  the value of order_task.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.id
	 * @param id  the value for order_task.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.order_number
	 * @return  the value of order_task.order_number
	 * @mbggenerated
	 */
	public String getOrderNumber() {
		return orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.order_number
	 * @param orderNumber  the value for order_task.order_number
	 * @mbggenerated
	 */
	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.create_date
	 * @return  the value of order_task.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.create_date
	 * @param createDate  the value for order_task.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.last_update_date
	 * @return  the value of order_task.last_update_date
	 * @mbggenerated
	 */
	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.last_update_date
	 * @param lastUpdateDate  the value for order_task.last_update_date
	 * @mbggenerated
	 */
	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.last_update_userid
	 * @return  the value of order_task.last_update_userid
	 * @mbggenerated
	 */
	public String getLastUpdateUserid() {
		return lastUpdateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.last_update_userid
	 * @param lastUpdateUserid  the value for order_task.last_update_userid
	 * @mbggenerated
	 */
	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.order_name
	 * @return  the value of order_task.order_name
	 * @mbggenerated
	 */
	public String getOrderName() {
		return orderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.order_name
	 * @param orderName  the value for order_task.order_name
	 * @mbggenerated
	 */
	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.status
	 * @return  the value of order_task.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.status
	 * @param status  the value for order_task.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.del_flag
	 * @return  the value of order_task.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.del_flag
	 * @param delFlag  the value for order_task.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.launcher_id
	 * @return  the value of order_task.launcher_id
	 * @mbggenerated
	 */
	public String getLauncherId() {
		return launcherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.launcher_id
	 * @param launcherId  the value for order_task.launcher_id
	 * @mbggenerated
	 */
	public void setLauncherId(String launcherId) {
		this.launcherId = launcherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.receiver_id
	 * @return  the value of order_task.receiver_id
	 * @mbggenerated
	 */
	public String getReceiverId() {
		return receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.receiver_id
	 * @param receiverId  the value for order_task.receiver_id
	 * @mbggenerated
	 */
	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.remark
	 * @return  the value of order_task.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.remark
	 * @param remark  the value for order_task.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.info_obli_1
	 * @return  the value of order_task.info_obli_1
	 * @mbggenerated
	 */
	public String getInfoObli1() {
		return infoObli1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.info_obli_1
	 * @param infoObli1  the value for order_task.info_obli_1
	 * @mbggenerated
	 */
	public void setInfoObli1(String infoObli1) {
		this.infoObli1 = infoObli1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.info_obli_2
	 * @return  the value of order_task.info_obli_2
	 * @mbggenerated
	 */
	public String getInfoObli2() {
		return infoObli2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.info_obli_2
	 * @param infoObli2  the value for order_task.info_obli_2
	 * @mbggenerated
	 */
	public void setInfoObli2(String infoObli2) {
		this.infoObli2 = infoObli2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.info_obli_3
	 * @return  the value of order_task.info_obli_3
	 * @mbggenerated
	 */
	public String getInfoObli3() {
		return infoObli3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.info_obli_3
	 * @param infoObli3  the value for order_task.info_obli_3
	 * @mbggenerated
	 */
	public void setInfoObli3(String infoObli3) {
		this.infoObli3 = infoObli3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.info_obli_4
	 * @return  the value of order_task.info_obli_4
	 * @mbggenerated
	 */
	public String getInfoObli4() {
		return infoObli4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.info_obli_4
	 * @param infoObli4  the value for order_task.info_obli_4
	 * @mbggenerated
	 */
	public void setInfoObli4(String infoObli4) {
		this.infoObli4 = infoObli4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.name
	 * @return  the value of order_task.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.name
	 * @param name  the value for order_task.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.description
	 * @return  the value of order_task.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.description
	 * @param description  the value for order_task.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.introduce
	 * @return  the value of order_task.introduce
	 * @mbggenerated
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.introduce
	 * @param introduce  the value for order_task.introduce
	 * @mbggenerated
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.type
	 * @return  the value of order_task.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.type
	 * @param type  the value for order_task.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.requirements
	 * @return  the value of order_task.requirements
	 * @mbggenerated
	 */
	public String getRequirements() {
		return requirements;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.requirements
	 * @param requirements  the value for order_task.requirements
	 * @mbggenerated
	 */
	public void setRequirements(String requirements) {
		this.requirements = requirements;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.money
	 * @return  the value of order_task.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.money
	 * @param money  the value for order_task.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.order_receiver_id
	 * @return  the value of order_task.order_receiver_id
	 * @mbggenerated
	 */
	public String getOrderReceiverId() {
		return orderReceiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.order_receiver_id
	 * @param orderReceiverId  the value for order_task.order_receiver_id
	 * @mbggenerated
	 */
	public void setOrderReceiverId(String orderReceiverId) {
		this.orderReceiverId = orderReceiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.end_time
	 * @return  the value of order_task.end_time
	 * @mbggenerated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.end_time
	 * @param endTime  the value for order_task.end_time
	 * @mbggenerated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.launcher_status
	 * @return  the value of order_task.launcher_status
	 * @mbggenerated
	 */
	public Byte getLauncherStatus() {
		return launcherStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.launcher_status
	 * @param launcherStatus  the value for order_task.launcher_status
	 * @mbggenerated
	 */
	public void setLauncherStatus(Byte launcherStatus) {
		this.launcherStatus = launcherStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.receiver_status
	 * @return  the value of order_task.receiver_status
	 * @mbggenerated
	 */
	public Byte getReceiverStatus() {
		return receiverStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.receiver_status
	 * @param receiverStatus  the value for order_task.receiver_status
	 * @mbggenerated
	 */
	public void setReceiverStatus(Byte receiverStatus) {
		this.receiverStatus = receiverStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.parent_id
	 * @return  the value of order_task.parent_id
	 * @mbggenerated
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.parent_id
	 * @param parentId  the value for order_task.parent_id
	 * @mbggenerated
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.icon_id
	 * @return  the value of order_task.icon_id
	 * @mbggenerated
	 */
	public String getIconId() {
		return iconId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.icon_id
	 * @param iconId  the value for order_task.icon_id
	 * @mbggenerated
	 */
	public void setIconId(String iconId) {
		this.iconId = iconId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.sort_num
	 * @return  the value of order_task.sort_num
	 * @mbggenerated
	 */
	public Integer getSortNum() {
		return sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.sort_num
	 * @param sortNum  the value for order_task.sort_num
	 * @mbggenerated
	 */
	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_task.orinin_money
	 * @return  the value of order_task.orinin_money
	 * @mbggenerated
	 */
	public Double getOrininMoney() {
		return orininMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_task.orinin_money
	 * @param orininMoney  the value for order_task.orinin_money
	 * @mbggenerated
	 */
	public void setOrininMoney(Double orininMoney) {
		this.orininMoney = orininMoney;
	}

	public  SysFile iconFile;
	
	public  SysFile attFile;

	public SysFile getAttFile() {
		return attFile;
	}

	public void setAttFile(SysFile attFile) {
		this.attFile = attFile;
	}

	public SysFile getIconFile() {
		return iconFile;
	}

	public void setIconFile(SysFile iconFile) {
		this.iconFile = iconFile;
	}
	
	private int sum;

	public int getSum() {
		return sum;
	}

	public void setSum(int sum) {
		this.sum = sum;
	}
	
	
}