package com.cishi.beans;

public class OrderReceiveInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.receiver_id
	 * @mbggenerated
	 */
	private String receiverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.order_id
	 * @mbggenerated
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.money
	 * @mbggenerated
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.is_current
	 * @mbggenerated
	 */
	private Boolean isCurrent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.parent_order_id
	 * @mbggenerated
	 */
	private String parentOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive_info.sys_confirm_id
	 * @mbggenerated
	 */
	private String sysConfirmId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.id
	 * @return  the value of order_receive_info.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.id
	 * @param id  the value for order_receive_info.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.receiver_id
	 * @return  the value of order_receive_info.receiver_id
	 * @mbggenerated
	 */
	public String getReceiverId() {
		return receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.receiver_id
	 * @param receiverId  the value for order_receive_info.receiver_id
	 * @mbggenerated
	 */
	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.order_id
	 * @return  the value of order_receive_info.order_id
	 * @mbggenerated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.order_id
	 * @param orderId  the value for order_receive_info.order_id
	 * @mbggenerated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.del_flag
	 * @return  the value of order_receive_info.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.del_flag
	 * @param delFlag  the value for order_receive_info.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.money
	 * @return  the value of order_receive_info.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.money
	 * @param money  the value for order_receive_info.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.is_current
	 * @return  the value of order_receive_info.is_current
	 * @mbggenerated
	 */
	public Boolean getIsCurrent() {
		return isCurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.is_current
	 * @param isCurrent  the value for order_receive_info.is_current
	 * @mbggenerated
	 */
	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.parent_order_id
	 * @return  the value of order_receive_info.parent_order_id
	 * @mbggenerated
	 */
	public String getParentOrderId() {
		return parentOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.parent_order_id
	 * @param parentOrderId  the value for order_receive_info.parent_order_id
	 * @mbggenerated
	 */
	public void setParentOrderId(String parentOrderId) {
		this.parentOrderId = parentOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive_info.sys_confirm_id
	 * @return  the value of order_receive_info.sys_confirm_id
	 * @mbggenerated
	 */
	public String getSysConfirmId() {
		return sysConfirmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive_info.sys_confirm_id
	 * @param sysConfirmId  the value for order_receive_info.sys_confirm_id
	 * @mbggenerated
	 */
	public void setSysConfirmId(String sysConfirmId) {
		this.sysConfirmId = sysConfirmId;
	}
}