package com.cishi.beans;

public class OrderTaskWithBLOBs extends OrderTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.requirements
     *
     * @mbggenerated
     */
    private String requirements;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.remark
     *
     * @return the value of order_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.remark
     *
     * @param remark the value for order_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.description
     *
     * @return the value of order_task.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.description
     *
     * @param description the value for order_task.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.introduce
     *
     * @return the value of order_task.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.introduce
     *
     * @param introduce the value for order_task.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.requirements
     *
     * @return the value of order_task.requirements
     *
     * @mbggenerated
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.requirements
     *
     * @param requirements the value for order_task.requirements
     *
     * @mbggenerated
     */
    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }
}