package com.cishi.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderTaskExample extends BaseExample{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_task
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_task
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_task
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public OrderTaskExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order_task
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("order_task.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("order_task.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("order_task.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("order_task.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("order_task.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("order_task.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("order_task.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("order_task.id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("order_task.id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("order_task.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("order_task.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("order_task.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("order_task.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderNumberIsNull() {
			addCriterion("order_task.order_number is null");
			return (Criteria) this;
		}

		public Criteria andOrderNumberIsNotNull() {
			addCriterion("order_task.order_number is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNumberEqualTo(String value) {
			addCriterion("order_task.order_number =", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotEqualTo(String value) {
			addCriterion("order_task.order_number <>", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberGreaterThan(String value) {
			addCriterion("order_task.order_number >", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.order_number >=", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberLessThan(String value) {
			addCriterion("order_task.order_number <", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberLessThanOrEqualTo(String value) {
			addCriterion("order_task.order_number <=", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberLike(String value) {
			addCriterion("order_task.order_number like", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotLike(String value) {
			addCriterion("order_task.order_number not like", value, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberIn(List<String> values) {
			addCriterion("order_task.order_number in", values, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotIn(List<String> values) {
			addCriterion("order_task.order_number not in", values, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberBetween(String value1, String value2) {
			addCriterion("order_task.order_number between", value1, value2, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andOrderNumberNotBetween(String value1, String value2) {
			addCriterion("order_task.order_number not between", value1, value2, "orderNumber");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("order_task.create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("order_task.create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("order_task.create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("order_task.create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("order_task.create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("order_task.create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("order_task.create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("order_task.create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("order_task.create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("order_task.create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("order_task.create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("order_task.create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateIsNull() {
			addCriterion("order_task.last_update_date is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateIsNotNull() {
			addCriterion("order_task.last_update_date is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateEqualTo(Date value) {
			addCriterion("order_task.last_update_date =", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateNotEqualTo(Date value) {
			addCriterion("order_task.last_update_date <>", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateGreaterThan(Date value) {
			addCriterion("order_task.last_update_date >", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("order_task.last_update_date >=", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateLessThan(Date value) {
			addCriterion("order_task.last_update_date <", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("order_task.last_update_date <=", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateIn(List<Date> values) {
			addCriterion("order_task.last_update_date in", values, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateNotIn(List<Date> values) {
			addCriterion("order_task.last_update_date not in", values, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
			addCriterion("order_task.last_update_date between", value1, value2, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("order_task.last_update_date not between", value1, value2, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridIsNull() {
			addCriterion("order_task.last_update_userid is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridIsNotNull() {
			addCriterion("order_task.last_update_userid is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridEqualTo(String value) {
			addCriterion("order_task.last_update_userid =", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridNotEqualTo(String value) {
			addCriterion("order_task.last_update_userid <>", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridGreaterThan(String value) {
			addCriterion("order_task.last_update_userid >", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.last_update_userid >=", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridLessThan(String value) {
			addCriterion("order_task.last_update_userid <", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridLessThanOrEqualTo(String value) {
			addCriterion("order_task.last_update_userid <=", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridLike(String value) {
			addCriterion("order_task.last_update_userid like", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridNotLike(String value) {
			addCriterion("order_task.last_update_userid not like", value, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridIn(List<String> values) {
			addCriterion("order_task.last_update_userid in", values, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridNotIn(List<String> values) {
			addCriterion("order_task.last_update_userid not in", values, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridBetween(String value1, String value2) {
			addCriterion("order_task.last_update_userid between", value1, value2, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andLastUpdateUseridNotBetween(String value1, String value2) {
			addCriterion("order_task.last_update_userid not between", value1, value2, "lastUpdateUserid");
			return (Criteria) this;
		}

		public Criteria andOrderNameIsNull() {
			addCriterion("order_task.order_name is null");
			return (Criteria) this;
		}

		public Criteria andOrderNameIsNotNull() {
			addCriterion("order_task.order_name is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNameEqualTo(String value) {
			addCriterion("order_task.order_name =", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotEqualTo(String value) {
			addCriterion("order_task.order_name <>", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameGreaterThan(String value) {
			addCriterion("order_task.order_name >", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.order_name >=", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLessThan(String value) {
			addCriterion("order_task.order_name <", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLessThanOrEqualTo(String value) {
			addCriterion("order_task.order_name <=", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameLike(String value) {
			addCriterion("order_task.order_name like", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotLike(String value) {
			addCriterion("order_task.order_name not like", value, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameIn(List<String> values) {
			addCriterion("order_task.order_name in", values, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotIn(List<String> values) {
			addCriterion("order_task.order_name not in", values, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameBetween(String value1, String value2) {
			addCriterion("order_task.order_name between", value1, value2, "orderName");
			return (Criteria) this;
		}

		public Criteria andOrderNameNotBetween(String value1, String value2) {
			addCriterion("order_task.order_name not between", value1, value2, "orderName");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("order_task.status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("order_task.status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("order_task.status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("order_task.status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("order_task.status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("order_task.status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("order_task.status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("order_task.status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("order_task.status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("order_task.status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("order_task.status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("order_task.status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("order_task.del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("order_task.del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("order_task.del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("order_task.del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("order_task.del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("order_task.del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("order_task.del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("order_task.del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("order_task.del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("order_task.del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("order_task.del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("order_task.del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andLauncherIdIsNull() {
			addCriterion("order_task.launcher_id is null");
			return (Criteria) this;
		}

		public Criteria andLauncherIdIsNotNull() {
			addCriterion("order_task.launcher_id is not null");
			return (Criteria) this;
		}

		public Criteria andLauncherIdEqualTo(String value) {
			addCriterion("order_task.launcher_id =", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdNotEqualTo(String value) {
			addCriterion("order_task.launcher_id <>", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdGreaterThan(String value) {
			addCriterion("order_task.launcher_id >", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.launcher_id >=", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdLessThan(String value) {
			addCriterion("order_task.launcher_id <", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdLessThanOrEqualTo(String value) {
			addCriterion("order_task.launcher_id <=", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdLike(String value) {
			addCriterion("order_task.launcher_id like", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdNotLike(String value) {
			addCriterion("order_task.launcher_id not like", value, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdIn(List<String> values) {
			addCriterion("order_task.launcher_id in", values, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdNotIn(List<String> values) {
			addCriterion("order_task.launcher_id not in", values, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdBetween(String value1, String value2) {
			addCriterion("order_task.launcher_id between", value1, value2, "launcherId");
			return (Criteria) this;
		}

		public Criteria andLauncherIdNotBetween(String value1, String value2) {
			addCriterion("order_task.launcher_id not between", value1, value2, "launcherId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdIsNull() {
			addCriterion("order_task.receiver_id is null");
			return (Criteria) this;
		}

		public Criteria andReceiverIdIsNotNull() {
			addCriterion("order_task.receiver_id is not null");
			return (Criteria) this;
		}

		public Criteria andReceiverIdEqualTo(String value) {
			addCriterion("order_task.receiver_id =", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdNotEqualTo(String value) {
			addCriterion("order_task.receiver_id <>", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdGreaterThan(String value) {
			addCriterion("order_task.receiver_id >", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.receiver_id >=", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdLessThan(String value) {
			addCriterion("order_task.receiver_id <", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdLessThanOrEqualTo(String value) {
			addCriterion("order_task.receiver_id <=", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdLike(String value) {
			addCriterion("order_task.receiver_id like", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdNotLike(String value) {
			addCriterion("order_task.receiver_id not like", value, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdIn(List<String> values) {
			addCriterion("order_task.receiver_id in", values, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdNotIn(List<String> values) {
			addCriterion("order_task.receiver_id not in", values, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdBetween(String value1, String value2) {
			addCriterion("order_task.receiver_id between", value1, value2, "receiverId");
			return (Criteria) this;
		}

		public Criteria andReceiverIdNotBetween(String value1, String value2) {
			addCriterion("order_task.receiver_id not between", value1, value2, "receiverId");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("order_task.remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("order_task.remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("order_task.remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("order_task.remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("order_task.remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("order_task.remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("order_task.remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("order_task.remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("order_task.remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("order_task.remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("order_task.remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("order_task.remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("order_task.remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andInfoObli1IsNull() {
			addCriterion("order_task.info_obli_1 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli1IsNotNull() {
			addCriterion("order_task.info_obli_1 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli1EqualTo(String value) {
			addCriterion("order_task.info_obli_1 =", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotEqualTo(String value) {
			addCriterion("order_task.info_obli_1 <>", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1GreaterThan(String value) {
			addCriterion("order_task.info_obli_1 >", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1GreaterThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_1 >=", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1LessThan(String value) {
			addCriterion("order_task.info_obli_1 <", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1LessThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_1 <=", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1Like(String value) {
			addCriterion("order_task.info_obli_1 like", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotLike(String value) {
			addCriterion("order_task.info_obli_1 not like", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1In(List<String> values) {
			addCriterion("order_task.info_obli_1 in", values, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotIn(List<String> values) {
			addCriterion("order_task.info_obli_1 not in", values, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1Between(String value1, String value2) {
			addCriterion("order_task.info_obli_1 between", value1, value2, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotBetween(String value1, String value2) {
			addCriterion("order_task.info_obli_1 not between", value1, value2, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli2IsNull() {
			addCriterion("order_task.info_obli_2 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli2IsNotNull() {
			addCriterion("order_task.info_obli_2 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli2EqualTo(String value) {
			addCriterion("order_task.info_obli_2 =", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotEqualTo(String value) {
			addCriterion("order_task.info_obli_2 <>", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2GreaterThan(String value) {
			addCriterion("order_task.info_obli_2 >", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2GreaterThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_2 >=", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2LessThan(String value) {
			addCriterion("order_task.info_obli_2 <", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2LessThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_2 <=", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2Like(String value) {
			addCriterion("order_task.info_obli_2 like", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotLike(String value) {
			addCriterion("order_task.info_obli_2 not like", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2In(List<String> values) {
			addCriterion("order_task.info_obli_2 in", values, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotIn(List<String> values) {
			addCriterion("order_task.info_obli_2 not in", values, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2Between(String value1, String value2) {
			addCriterion("order_task.info_obli_2 between", value1, value2, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotBetween(String value1, String value2) {
			addCriterion("order_task.info_obli_2 not between", value1, value2, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli3IsNull() {
			addCriterion("order_task.info_obli_3 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli3IsNotNull() {
			addCriterion("order_task.info_obli_3 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli3EqualTo(String value) {
			addCriterion("order_task.info_obli_3 =", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotEqualTo(String value) {
			addCriterion("order_task.info_obli_3 <>", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3GreaterThan(String value) {
			addCriterion("order_task.info_obli_3 >", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3GreaterThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_3 >=", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3LessThan(String value) {
			addCriterion("order_task.info_obli_3 <", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3LessThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_3 <=", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3Like(String value) {
			addCriterion("order_task.info_obli_3 like", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotLike(String value) {
			addCriterion("order_task.info_obli_3 not like", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3In(List<String> values) {
			addCriterion("order_task.info_obli_3 in", values, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotIn(List<String> values) {
			addCriterion("order_task.info_obli_3 not in", values, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3Between(String value1, String value2) {
			addCriterion("order_task.info_obli_3 between", value1, value2, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotBetween(String value1, String value2) {
			addCriterion("order_task.info_obli_3 not between", value1, value2, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli4IsNull() {
			addCriterion("order_task.info_obli_4 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli4IsNotNull() {
			addCriterion("order_task.info_obli_4 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli4EqualTo(String value) {
			addCriterion("order_task.info_obli_4 =", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotEqualTo(String value) {
			addCriterion("order_task.info_obli_4 <>", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4GreaterThan(String value) {
			addCriterion("order_task.info_obli_4 >", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4GreaterThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_4 >=", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4LessThan(String value) {
			addCriterion("order_task.info_obli_4 <", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4LessThanOrEqualTo(String value) {
			addCriterion("order_task.info_obli_4 <=", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4Like(String value) {
			addCriterion("order_task.info_obli_4 like", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotLike(String value) {
			addCriterion("order_task.info_obli_4 not like", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4In(List<String> values) {
			addCriterion("order_task.info_obli_4 in", values, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotIn(List<String> values) {
			addCriterion("order_task.info_obli_4 not in", values, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4Between(String value1, String value2) {
			addCriterion("order_task.info_obli_4 between", value1, value2, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotBetween(String value1, String value2) {
			addCriterion("order_task.info_obli_4 not between", value1, value2, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("order_task.name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("order_task.name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("order_task.name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("order_task.name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("order_task.name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("order_task.name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("order_task.name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("order_task.name like", value, "name");
			return (Criteria) this;
		}

		public Criteria orNameListIn(String value,List<Byte> list) {
			if(list==null || list.size()<=0){
				return this.andNameLike("%"+value+"%");
			}
			StringBuffer sb = new StringBuffer();
			sb.append("(");
			for(int i=0;i<list.size();i++){
				Byte b = list.get(i);
				sb.append(b);
				if(i<list.size()-1){
					sb.append(",");
				}
			}
			sb.append(")");
			addCriterion("(order_task.name like '%"+value+"%' or order_task.type in "+sb.toString()+")");
			return (Criteria) this;
		}
		
		public Criteria andNameNotLike(String value) {
			addCriterion("order_task.name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("order_task.name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("order_task.name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("order_task.name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("order_task.name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("order_task.description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("order_task.description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("order_task.description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("order_task.description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("order_task.description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("order_task.description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("order_task.description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("order_task.description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("order_task.description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("order_task.description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("order_task.description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("order_task.description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("order_task.description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andIntroduceIsNull() {
			addCriterion("order_task.introduce is null");
			return (Criteria) this;
		}

		public Criteria andIntroduceIsNotNull() {
			addCriterion("order_task.introduce is not null");
			return (Criteria) this;
		}

		public Criteria andIntroduceEqualTo(String value) {
			addCriterion("order_task.introduce =", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotEqualTo(String value) {
			addCriterion("order_task.introduce <>", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceGreaterThan(String value) {
			addCriterion("order_task.introduce >", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.introduce >=", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLessThan(String value) {
			addCriterion("order_task.introduce <", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLessThanOrEqualTo(String value) {
			addCriterion("order_task.introduce <=", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLike(String value) {
			addCriterion("order_task.introduce like", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotLike(String value) {
			addCriterion("order_task.introduce not like", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceIn(List<String> values) {
			addCriterion("order_task.introduce in", values, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotIn(List<String> values) {
			addCriterion("order_task.introduce not in", values, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceBetween(String value1, String value2) {
			addCriterion("order_task.introduce between", value1, value2, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotBetween(String value1, String value2) {
			addCriterion("order_task.introduce not between", value1, value2, "introduce");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("order_task.type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("order_task.type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Byte value) {
			addCriterion("order_task.type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Byte value) {
			addCriterion("order_task.type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Byte value) {
			addCriterion("order_task.type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("order_task.type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Byte value) {
			addCriterion("order_task.type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Byte value) {
			addCriterion("order_task.type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Byte> values) {
			addCriterion("order_task.type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Byte> values) {
			addCriterion("order_task.type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Byte value1, Byte value2) {
			addCriterion("order_task.type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("order_task.type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andRequirementsIsNull() {
			addCriterion("order_task.requirements is null");
			return (Criteria) this;
		}

		public Criteria andRequirementsIsNotNull() {
			addCriterion("order_task.requirements is not null");
			return (Criteria) this;
		}

		public Criteria andRequirementsEqualTo(String value) {
			addCriterion("order_task.requirements =", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsNotEqualTo(String value) {
			addCriterion("order_task.requirements <>", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsGreaterThan(String value) {
			addCriterion("order_task.requirements >", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.requirements >=", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsLessThan(String value) {
			addCriterion("order_task.requirements <", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsLessThanOrEqualTo(String value) {
			addCriterion("order_task.requirements <=", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsLike(String value) {
			addCriterion("order_task.requirements like", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsNotLike(String value) {
			addCriterion("order_task.requirements not like", value, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsIn(List<String> values) {
			addCriterion("order_task.requirements in", values, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsNotIn(List<String> values) {
			addCriterion("order_task.requirements not in", values, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsBetween(String value1, String value2) {
			addCriterion("order_task.requirements between", value1, value2, "requirements");
			return (Criteria) this;
		}

		public Criteria andRequirementsNotBetween(String value1, String value2) {
			addCriterion("order_task.requirements not between", value1, value2, "requirements");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("order_task.money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("order_task.money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Double value) {
			addCriterion("order_task.money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Double value) {
			addCriterion("order_task.money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Double value) {
			addCriterion("order_task.money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("order_task.money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Double value) {
			addCriterion("order_task.money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Double value) {
			addCriterion("order_task.money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Double> values) {
			addCriterion("order_task.money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Double> values) {
			addCriterion("order_task.money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Double value1, Double value2) {
			addCriterion("order_task.money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Double value1, Double value2) {
			addCriterion("order_task.money not between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdIsNull() {
			addCriterion("order_task.order_receiver_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdIsNotNull() {
			addCriterion("order_task.order_receiver_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdEqualTo(String value) {
			addCriterion("order_task.order_receiver_id =", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdNotEqualTo(String value) {
			addCriterion("order_task.order_receiver_id <>", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdGreaterThan(String value) {
			addCriterion("order_task.order_receiver_id >", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.order_receiver_id >=", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdLessThan(String value) {
			addCriterion("order_task.order_receiver_id <", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdLessThanOrEqualTo(String value) {
			addCriterion("order_task.order_receiver_id <=", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdLike(String value) {
			addCriterion("order_task.order_receiver_id like", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdNotLike(String value) {
			addCriterion("order_task.order_receiver_id not like", value, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdIn(List<String> values) {
			addCriterion("order_task.order_receiver_id in", values, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdNotIn(List<String> values) {
			addCriterion("order_task.order_receiver_id not in", values, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdBetween(String value1, String value2) {
			addCriterion("order_task.order_receiver_id between", value1, value2, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andOrderReceiverIdNotBetween(String value1, String value2) {
			addCriterion("order_task.order_receiver_id not between", value1, value2, "orderReceiverId");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("order_task.end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("order_task.end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("order_task.end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("order_task.end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("order_task.end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("order_task.end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("order_task.end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("order_task.end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("order_task.end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("order_task.end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("order_task.end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("order_task.end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusIsNull() {
			addCriterion("order_task.launcher_status is null");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusIsNotNull() {
			addCriterion("order_task.launcher_status is not null");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusEqualTo(Byte value) {
			addCriterion("order_task.launcher_status =", value, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusNotEqualTo(Byte value) {
			addCriterion("order_task.launcher_status <>", value, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusGreaterThan(Byte value) {
			addCriterion("order_task.launcher_status >", value, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("order_task.launcher_status >=", value, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusLessThan(Byte value) {
			addCriterion("order_task.launcher_status <", value, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusLessThanOrEqualTo(Byte value) {
			addCriterion("order_task.launcher_status <=", value, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusIn(List<Byte> values) {
			addCriterion("order_task.launcher_status in", values, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusNotIn(List<Byte> values) {
			addCriterion("order_task.launcher_status not in", values, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusBetween(Byte value1, Byte value2) {
			addCriterion("order_task.launcher_status between", value1, value2, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andLauncherStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("order_task.launcher_status not between", value1, value2, "launcherStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusIsNull() {
			addCriterion("order_task.receiver_status is null");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusIsNotNull() {
			addCriterion("order_task.receiver_status is not null");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusEqualTo(Byte value) {
			addCriterion("order_task.receiver_status =", value, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusNotEqualTo(Byte value) {
			addCriterion("order_task.receiver_status <>", value, "receiverStatus");
			return (Criteria) this;
		}
		
		public Criteria andChildNotEq(){
			addCriterion("order_task.id in ( SELECT parent_id FROM order_task WHERE parent_id != '-1' AND parent_id IS NOT NULL AND parent_id != '' AND STATUS != '7' AND del_flag != '1' GROUP BY parent_id ) ");
			return (Criteria) this;
		}
		public Criteria andChildEq(){
			addCriterion("order_task.id in ( SELECT parent_id FROM order_task WHERE parent_id != '-1' AND parent_id IS NOT NULL AND parent_id != '' AND STATUS = '7' AND del_flag != '1' GROUP BY parent_id ) ");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusGreaterThan(Byte value) {
			addCriterion("order_task.receiver_status >", value, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("order_task.receiver_status >=", value, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusLessThan(Byte value) {
			addCriterion("order_task.receiver_status <", value, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusLessThanOrEqualTo(Byte value) {
			addCriterion("order_task.receiver_status <=", value, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusIn(List<Byte> values) {
			addCriterion("order_task.receiver_status in", values, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusNotIn(List<Byte> values) {
			addCriterion("order_task.receiver_status not in", values, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusBetween(Byte value1, Byte value2) {
			addCriterion("order_task.receiver_status between", value1, value2, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andReceiverStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("order_task.receiver_status not between", value1, value2, "receiverStatus");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("order_task.parent_id is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("order_task.parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(String value) {
			addCriterion("order_task.parent_id =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(String value) {
			addCriterion("order_task.parent_id <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(String value) {
			addCriterion("order_task.parent_id >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.parent_id >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(String value) {
			addCriterion("order_task.parent_id <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(String value) {
			addCriterion("order_task.parent_id <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLike(String value) {
			addCriterion("order_task.parent_id like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotLike(String value) {
			addCriterion("order_task.parent_id not like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<String> values) {
			addCriterion("order_task.parent_id in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<String> values) {
			addCriterion("order_task.parent_id not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(String value1, String value2) {
			addCriterion("order_task.parent_id between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(String value1, String value2) {
			addCriterion("order_task.parent_id not between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andIconIdIsNull() {
			addCriterion("order_task.icon_id is null");
			return (Criteria) this;
		}

		public Criteria andIconIdIsNotNull() {
			addCriterion("order_task.icon_id is not null");
			return (Criteria) this;
		}

		public Criteria andIconIdEqualTo(String value) {
			addCriterion("order_task.icon_id =", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdNotEqualTo(String value) {
			addCriterion("order_task.icon_id <>", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdGreaterThan(String value) {
			addCriterion("order_task.icon_id >", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_task.icon_id >=", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdLessThan(String value) {
			addCriterion("order_task.icon_id <", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdLessThanOrEqualTo(String value) {
			addCriterion("order_task.icon_id <=", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdLike(String value) {
			addCriterion("order_task.icon_id like", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdNotLike(String value) {
			addCriterion("order_task.icon_id not like", value, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdIn(List<String> values) {
			addCriterion("order_task.icon_id in", values, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdNotIn(List<String> values) {
			addCriterion("order_task.icon_id not in", values, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdBetween(String value1, String value2) {
			addCriterion("order_task.icon_id between", value1, value2, "iconId");
			return (Criteria) this;
		}

		public Criteria andIconIdNotBetween(String value1, String value2) {
			addCriterion("order_task.icon_id not between", value1, value2, "iconId");
			return (Criteria) this;
		}

		public Criteria andSortNumIsNull() {
			addCriterion("order_task.sort_num is null");
			return (Criteria) this;
		}

		public Criteria andSortNumIsNotNull() {
			addCriterion("order_task.sort_num is not null");
			return (Criteria) this;
		}

		public Criteria andSortNumEqualTo(Integer value) {
			addCriterion("order_task.sort_num =", value, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumNotEqualTo(Integer value) {
			addCriterion("order_task.sort_num <>", value, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumGreaterThan(Integer value) {
			addCriterion("order_task.sort_num >", value, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_task.sort_num >=", value, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumLessThan(Integer value) {
			addCriterion("order_task.sort_num <", value, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumLessThanOrEqualTo(Integer value) {
			addCriterion("order_task.sort_num <=", value, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumIn(List<Integer> values) {
			addCriterion("order_task.sort_num in", values, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumNotIn(List<Integer> values) {
			addCriterion("order_task.sort_num not in", values, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumBetween(Integer value1, Integer value2) {
			addCriterion("order_task.sort_num between", value1, value2, "sortNum");
			return (Criteria) this;
		}

		public Criteria andSortNumNotBetween(Integer value1, Integer value2) {
			addCriterion("order_task.sort_num not between", value1, value2, "sortNum");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyIsNull() {
			addCriterion("order_task.orinin_money is null");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyIsNotNull() {
			addCriterion("order_task.orinin_money is not null");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyEqualTo(Double value) {
			addCriterion("order_task.orinin_money =", value, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyNotEqualTo(Double value) {
			addCriterion("order_task.orinin_money <>", value, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyGreaterThan(Double value) {
			addCriterion("order_task.orinin_money >", value, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("order_task.orinin_money >=", value, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyLessThan(Double value) {
			addCriterion("order_task.orinin_money <", value, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyLessThanOrEqualTo(Double value) {
			addCriterion("order_task.orinin_money <=", value, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyIn(List<Double> values) {
			addCriterion("order_task.orinin_money in", values, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyNotIn(List<Double> values) {
			addCriterion("order_task.orinin_money not in", values, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyBetween(Double value1, Double value2) {
			addCriterion("order_task.orinin_money between", value1, value2, "orininMoney");
			return (Criteria) this;
		}

		public Criteria andOrininMoneyNotBetween(Double value1, Double value2) {
			addCriterion("order_task.orinin_money not between", value1, value2, "orininMoney");
			return (Criteria) this;
		}
		public Criteria andOrderReceiveIdEqual(String value1) {
			addCriterion("order_task.receiver_id =", value1,null);
			return (Criteria) this;
		}
		
		public Criteria andSysConfirmTypeEqual(Byte value1) {
			addCriterion("order_task.type =", value1,null);
			return (Criteria) this;
		}
		
		public Criteria andComplateEqualTotal(boolean flag) {
			if(flag){
				addCriterion("complate=total");
			}
			return (Criteria) this;
		}
		
		public Criteria andComplateNotEqualTotal(boolean flag) {
			if(flag){
				addCriterion("complate!=total");
			}
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order_task
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	protected Criteria criteria;
	

	public Criteria getCriteria() {
		return criteria;
	}
	
	public Criteria getCriteriaFirst(){
		return oredCriteria.get(0);
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_task
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}