package com.cishi.beans;

import java.util.Date;

public class OrderReceive {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.order_id
	 * @mbggenerated
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.receiver_id
	 * @mbggenerated
	 */
	private String receiverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.info_obli_1
	 * @mbggenerated
	 */
	private String infoObli1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.info_obli_2
	 * @mbggenerated
	 */
	private String infoObli2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.info_obli_3
	 * @mbggenerated
	 */
	private String infoObli3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.info_obli_4
	 * @mbggenerated
	 */
	private String infoObli4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.money
	 * @mbggenerated
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receive.receive_status
	 * @mbggenerated
	 */
	private Byte receiveStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.id
	 * @return  the value of order_receive.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.id
	 * @param id  the value for order_receive.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.order_id
	 * @return  the value of order_receive.order_id
	 * @mbggenerated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.order_id
	 * @param orderId  the value for order_receive.order_id
	 * @mbggenerated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.create_date
	 * @return  the value of order_receive.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.create_date
	 * @param createDate  the value for order_receive.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.receiver_id
	 * @return  the value of order_receive.receiver_id
	 * @mbggenerated
	 */
	public String getReceiverId() {
		return receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.receiver_id
	 * @param receiverId  the value for order_receive.receiver_id
	 * @mbggenerated
	 */
	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.del_flag
	 * @return  the value of order_receive.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.del_flag
	 * @param delFlag  the value for order_receive.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.remark
	 * @return  the value of order_receive.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.remark
	 * @param remark  the value for order_receive.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.info_obli_1
	 * @return  the value of order_receive.info_obli_1
	 * @mbggenerated
	 */
	public String getInfoObli1() {
		return infoObli1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.info_obli_1
	 * @param infoObli1  the value for order_receive.info_obli_1
	 * @mbggenerated
	 */
	public void setInfoObli1(String infoObli1) {
		this.infoObli1 = infoObli1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.info_obli_2
	 * @return  the value of order_receive.info_obli_2
	 * @mbggenerated
	 */
	public String getInfoObli2() {
		return infoObli2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.info_obli_2
	 * @param infoObli2  the value for order_receive.info_obli_2
	 * @mbggenerated
	 */
	public void setInfoObli2(String infoObli2) {
		this.infoObli2 = infoObli2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.info_obli_3
	 * @return  the value of order_receive.info_obli_3
	 * @mbggenerated
	 */
	public String getInfoObli3() {
		return infoObli3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.info_obli_3
	 * @param infoObli3  the value for order_receive.info_obli_3
	 * @mbggenerated
	 */
	public void setInfoObli3(String infoObli3) {
		this.infoObli3 = infoObli3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.info_obli_4
	 * @return  the value of order_receive.info_obli_4
	 * @mbggenerated
	 */
	public String getInfoObli4() {
		return infoObli4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.info_obli_4
	 * @param infoObli4  the value for order_receive.info_obli_4
	 * @mbggenerated
	 */
	public void setInfoObli4(String infoObli4) {
		this.infoObli4 = infoObli4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.money
	 * @return  the value of order_receive.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.money
	 * @param money  the value for order_receive.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receive.receive_status
	 * @return  the value of order_receive.receive_status
	 * @mbggenerated
	 */
	public Byte getReceiveStatus() {
		return receiveStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receive.receive_status
	 * @param receiveStatus  the value for order_receive.receive_status
	 * @mbggenerated
	 */
	public void setReceiveStatus(Byte receiveStatus) {
		this.receiveStatus = receiveStatus;
	}
}