package com.cishi.beans;

import java.util.Date;

public class SysAccountDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.money
	 * @mbggenerated
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.receiver_id
	 * @mbggenerated
	 */
	private String receiverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.type
	 * @mbggenerated
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.pay_type
	 * @mbggenerated
	 */
	private Byte payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account_detail.account
	 * @mbggenerated
	 */
	private String account;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.id
	 * @return  the value of sys_account_detail.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.id
	 * @param id  the value for sys_account_detail.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.user_id
	 * @return  the value of sys_account_detail.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.user_id
	 * @param userId  the value for sys_account_detail.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.money
	 * @return  the value of sys_account_detail.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.money
	 * @param money  the value for sys_account_detail.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.del_flag
	 * @return  the value of sys_account_detail.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.del_flag
	 * @param delFlag  the value for sys_account_detail.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.create_date
	 * @return  the value of sys_account_detail.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.create_date
	 * @param createDate  the value for sys_account_detail.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.receiver_id
	 * @return  the value of sys_account_detail.receiver_id
	 * @mbggenerated
	 */
	public String getReceiverId() {
		return receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.receiver_id
	 * @param receiverId  the value for sys_account_detail.receiver_id
	 * @mbggenerated
	 */
	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.type
	 * @return  the value of sys_account_detail.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.type
	 * @param type  the value for sys_account_detail.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.status
	 * @return  the value of sys_account_detail.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.status
	 * @param status  the value for sys_account_detail.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.pay_type
	 * @return  the value of sys_account_detail.pay_type
	 * @mbggenerated
	 */
	public Byte getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.pay_type
	 * @param payType  the value for sys_account_detail.pay_type
	 * @mbggenerated
	 */
	public void setPayType(Byte payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.remark
	 * @return  the value of sys_account_detail.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.remark
	 * @param remark  the value for sys_account_detail.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account_detail.account
	 * @return  the value of sys_account_detail.account
	 * @mbggenerated
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account_detail.account
	 * @param account  the value for sys_account_detail.account
	 * @mbggenerated
	 */
	public void setAccount(String account) {
		this.account = account;
	}
}