package com.cishi.beans;

public class SysCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.company_name
	 * @mbggenerated
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.login_name
	 * @mbggenerated
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.phone_number
	 * @mbggenerated
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.STATUS
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.info_obli_1
	 * @mbggenerated
	 */
	private String infoObli1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.info_obli_2
	 * @mbggenerated
	 */
	private String infoObli2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.info_obli_3
	 * @mbggenerated
	 */
	private String infoObli3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.info_obli_4
	 * @mbggenerated
	 */
	private String infoObli4;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.id
	 * @return  the value of sys_company.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.id
	 * @param id  the value for sys_company.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.company_name
	 * @return  the value of sys_company.company_name
	 * @mbggenerated
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.company_name
	 * @param companyName  the value for sys_company.company_name
	 * @mbggenerated
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.login_name
	 * @return  the value of sys_company.login_name
	 * @mbggenerated
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.login_name
	 * @param loginName  the value for sys_company.login_name
	 * @mbggenerated
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.phone_number
	 * @return  the value of sys_company.phone_number
	 * @mbggenerated
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.phone_number
	 * @param phoneNumber  the value for sys_company.phone_number
	 * @mbggenerated
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.del_flag
	 * @return  the value of sys_company.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.del_flag
	 * @param delFlag  the value for sys_company.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.STATUS
	 * @return  the value of sys_company.STATUS
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.STATUS
	 * @param status  the value for sys_company.STATUS
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.info_obli_1
	 * @return  the value of sys_company.info_obli_1
	 * @mbggenerated
	 */
	public String getInfoObli1() {
		return infoObli1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.info_obli_1
	 * @param infoObli1  the value for sys_company.info_obli_1
	 * @mbggenerated
	 */
	public void setInfoObli1(String infoObli1) {
		this.infoObli1 = infoObli1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.info_obli_2
	 * @return  the value of sys_company.info_obli_2
	 * @mbggenerated
	 */
	public String getInfoObli2() {
		return infoObli2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.info_obli_2
	 * @param infoObli2  the value for sys_company.info_obli_2
	 * @mbggenerated
	 */
	public void setInfoObli2(String infoObli2) {
		this.infoObli2 = infoObli2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.info_obli_3
	 * @return  the value of sys_company.info_obli_3
	 * @mbggenerated
	 */
	public String getInfoObli3() {
		return infoObli3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.info_obli_3
	 * @param infoObli3  the value for sys_company.info_obli_3
	 * @mbggenerated
	 */
	public void setInfoObli3(String infoObli3) {
		this.infoObli3 = infoObli3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.info_obli_4
	 * @return  the value of sys_company.info_obli_4
	 * @mbggenerated
	 */
	public String getInfoObli4() {
		return infoObli4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.info_obli_4
	 * @param infoObli4  the value for sys_company.info_obli_4
	 * @mbggenerated
	 */
	public void setInfoObli4(String infoObli4) {
		this.infoObli4 = infoObli4;
	}
}