package com.cishi.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysConfirmExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public SysConfirmExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("sys_confirm.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("sys_confirm.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("sys_confirm.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("sys_confirm.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("sys_confirm.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("sys_confirm.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("sys_confirm.id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("sys_confirm.id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("sys_confirm.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("sys_confirm.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("sys_confirm.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("sys_confirm.order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("sys_confirm.order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("sys_confirm.order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("sys_confirm.order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("sys_confirm.order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("sys_confirm.order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("sys_confirm.order_id like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("sys_confirm.order_id not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("sys_confirm.order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("sys_confirm.order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("sys_confirm.order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdIsNull() {
			addCriterion("sys_confirm.one_partner_id is null");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdIsNotNull() {
			addCriterion("sys_confirm.one_partner_id is not null");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdEqualTo(String value) {
			addCriterion("sys_confirm.one_partner_id =", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdNotEqualTo(String value) {
			addCriterion("sys_confirm.one_partner_id <>", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdGreaterThan(String value) {
			addCriterion("sys_confirm.one_partner_id >", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.one_partner_id >=", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdLessThan(String value) {
			addCriterion("sys_confirm.one_partner_id <", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.one_partner_id <=", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdLike(String value) {
			addCriterion("sys_confirm.one_partner_id like", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdNotLike(String value) {
			addCriterion("sys_confirm.one_partner_id not like", value, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdIn(List<String> values) {
			addCriterion("sys_confirm.one_partner_id in", values, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdNotIn(List<String> values) {
			addCriterion("sys_confirm.one_partner_id not in", values, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdBetween(String value1, String value2) {
			addCriterion("sys_confirm.one_partner_id between", value1, value2, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andOnePartnerIdNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.one_partner_id not between", value1, value2, "onePartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdIsNull() {
			addCriterion("sys_confirm.sec_partner_id is null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdIsNotNull() {
			addCriterion("sys_confirm.sec_partner_id is not null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_id =", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdNotEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_id <>", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdGreaterThan(String value) {
			addCriterion("sys_confirm.sec_partner_id >", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_id >=", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdLessThan(String value) {
			addCriterion("sys_confirm.sec_partner_id <", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_id <=", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdLike(String value) {
			addCriterion("sys_confirm.sec_partner_id like", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdNotLike(String value) {
			addCriterion("sys_confirm.sec_partner_id not like", value, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdIn(List<String> values) {
			addCriterion("sys_confirm.sec_partner_id in", values, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdNotIn(List<String> values) {
			addCriterion("sys_confirm.sec_partner_id not in", values, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdBetween(String value1, String value2) {
			addCriterion("sys_confirm.sec_partner_id between", value1, value2, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andSecPartnerIdNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.sec_partner_id not between", value1, value2, "secPartnerId");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("sys_confirm.del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("sys_confirm.del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("sys_confirm.del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("sys_confirm.del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("sys_confirm.del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("sys_confirm.del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusIsNull() {
			addCriterion("sys_confirm.one_partner_status is null");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusIsNotNull() {
			addCriterion("sys_confirm.one_partner_status is not null");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusEqualTo(Byte value) {
			addCriterion("sys_confirm.one_partner_status =", value, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusNotEqualTo(Byte value) {
			addCriterion("sys_confirm.one_partner_status <>", value, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusGreaterThan(Byte value) {
			addCriterion("sys_confirm.one_partner_status >", value, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.one_partner_status >=", value, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusLessThan(Byte value) {
			addCriterion("sys_confirm.one_partner_status <", value, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.one_partner_status <=", value, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusIn(List<Byte> values) {
			addCriterion("sys_confirm.one_partner_status in", values, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusNotIn(List<Byte> values) {
			addCriterion("sys_confirm.one_partner_status not in", values, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.one_partner_status between", value1, value2, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnePartnerStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.one_partner_status not between", value1, value2, "onePartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusIsNull() {
			addCriterion("sys_confirm.sec_partner_status is null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusIsNotNull() {
			addCriterion("sys_confirm.sec_partner_status is not null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusEqualTo(Byte value) {
			addCriterion("sys_confirm.sec_partner_status =", value, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusNotEqualTo(Byte value) {
			addCriterion("sys_confirm.sec_partner_status <>", value, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusGreaterThan(Byte value) {
			addCriterion("sys_confirm.sec_partner_status >", value, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.sec_partner_status >=", value, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusLessThan(Byte value) {
			addCriterion("sys_confirm.sec_partner_status <", value, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.sec_partner_status <=", value, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusIn(List<Byte> values) {
			addCriterion("sys_confirm.sec_partner_status in", values, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusNotIn(List<Byte> values) {
			addCriterion("sys_confirm.sec_partner_status not in", values, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.sec_partner_status between", value1, value2, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andSecPartnerStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.sec_partner_status not between", value1, value2, "secPartnerStatus");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkIsNull() {
			addCriterion("sys_confirm.on_partner_remark is null");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkIsNotNull() {
			addCriterion("sys_confirm.on_partner_remark is not null");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkEqualTo(String value) {
			addCriterion("sys_confirm.on_partner_remark =", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkNotEqualTo(String value) {
			addCriterion("sys_confirm.on_partner_remark <>", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkGreaterThan(String value) {
			addCriterion("sys_confirm.on_partner_remark >", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.on_partner_remark >=", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkLessThan(String value) {
			addCriterion("sys_confirm.on_partner_remark <", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.on_partner_remark <=", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkLike(String value) {
			addCriterion("sys_confirm.on_partner_remark like", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkNotLike(String value) {
			addCriterion("sys_confirm.on_partner_remark not like", value, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkIn(List<String> values) {
			addCriterion("sys_confirm.on_partner_remark in", values, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkNotIn(List<String> values) {
			addCriterion("sys_confirm.on_partner_remark not in", values, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkBetween(String value1, String value2) {
			addCriterion("sys_confirm.on_partner_remark between", value1, value2, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnPartnerRemarkNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.on_partner_remark not between", value1, value2, "onPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkIsNull() {
			addCriterion("sys_confirm.sec_partner_remark is null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkIsNotNull() {
			addCriterion("sys_confirm.sec_partner_remark is not null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_remark =", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkNotEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_remark <>", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkGreaterThan(String value) {
			addCriterion("sys_confirm.sec_partner_remark >", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_remark >=", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkLessThan(String value) {
			addCriterion("sys_confirm.sec_partner_remark <", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.sec_partner_remark <=", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkLike(String value) {
			addCriterion("sys_confirm.sec_partner_remark like", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkNotLike(String value) {
			addCriterion("sys_confirm.sec_partner_remark not like", value, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkIn(List<String> values) {
			addCriterion("sys_confirm.sec_partner_remark in", values, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkNotIn(List<String> values) {
			addCriterion("sys_confirm.sec_partner_remark not in", values, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkBetween(String value1, String value2) {
			addCriterion("sys_confirm.sec_partner_remark between", value1, value2, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andSecPartnerRemarkNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.sec_partner_remark not between", value1, value2, "secPartnerRemark");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateIsNull() {
			addCriterion("sys_confirm.one_partner_date is null");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateIsNotNull() {
			addCriterion("sys_confirm.one_partner_date is not null");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateEqualTo(Date value) {
			addCriterion("sys_confirm.one_partner_date =", value, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateNotEqualTo(Date value) {
			addCriterion("sys_confirm.one_partner_date <>", value, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateGreaterThan(Date value) {
			addCriterion("sys_confirm.one_partner_date >", value, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateGreaterThanOrEqualTo(Date value) {
			addCriterion("sys_confirm.one_partner_date >=", value, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateLessThan(Date value) {
			addCriterion("sys_confirm.one_partner_date <", value, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateLessThanOrEqualTo(Date value) {
			addCriterion("sys_confirm.one_partner_date <=", value, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateIn(List<Date> values) {
			addCriterion("sys_confirm.one_partner_date in", values, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateNotIn(List<Date> values) {
			addCriterion("sys_confirm.one_partner_date not in", values, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateBetween(Date value1, Date value2) {
			addCriterion("sys_confirm.one_partner_date between", value1, value2, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andOnePartnerDateNotBetween(Date value1, Date value2) {
			addCriterion("sys_confirm.one_partner_date not between", value1, value2, "onePartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateIsNull() {
			addCriterion("sys_confirm.sec_partner_date is null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateIsNotNull() {
			addCriterion("sys_confirm.sec_partner_date is not null");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateEqualTo(Date value) {
			addCriterion("sys_confirm.sec_partner_date =", value, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateNotEqualTo(Date value) {
			addCriterion("sys_confirm.sec_partner_date <>", value, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateGreaterThan(Date value) {
			addCriterion("sys_confirm.sec_partner_date >", value, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateGreaterThanOrEqualTo(Date value) {
			addCriterion("sys_confirm.sec_partner_date >=", value, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateLessThan(Date value) {
			addCriterion("sys_confirm.sec_partner_date <", value, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateLessThanOrEqualTo(Date value) {
			addCriterion("sys_confirm.sec_partner_date <=", value, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateIn(List<Date> values) {
			addCriterion("sys_confirm.sec_partner_date in", values, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateNotIn(List<Date> values) {
			addCriterion("sys_confirm.sec_partner_date not in", values, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateBetween(Date value1, Date value2) {
			addCriterion("sys_confirm.sec_partner_date between", value1, value2, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andSecPartnerDateNotBetween(Date value1, Date value2) {
			addCriterion("sys_confirm.sec_partner_date not between", value1, value2, "secPartnerDate");
			return (Criteria) this;
		}

		public Criteria andIsCurrentIsNull() {
			addCriterion("sys_confirm.is_current is null");
			return (Criteria) this;
		}

		public Criteria andIsCurrentIsNotNull() {
			addCriterion("sys_confirm.is_current is not null");
			return (Criteria) this;
		}

		public Criteria andIsCurrentEqualTo(Boolean value) {
			addCriterion("sys_confirm.is_current =", value, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentNotEqualTo(Boolean value) {
			addCriterion("sys_confirm.is_current <>", value, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentGreaterThan(Boolean value) {
			addCriterion("sys_confirm.is_current >", value, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentGreaterThanOrEqualTo(Boolean value) {
			addCriterion("sys_confirm.is_current >=", value, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentLessThan(Boolean value) {
			addCriterion("sys_confirm.is_current <", value, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentLessThanOrEqualTo(Boolean value) {
			addCriterion("sys_confirm.is_current <=", value, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentIn(List<Boolean> values) {
			addCriterion("sys_confirm.is_current in", values, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentNotIn(List<Boolean> values) {
			addCriterion("sys_confirm.is_current not in", values, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentBetween(Boolean value1, Boolean value2) {
			addCriterion("sys_confirm.is_current between", value1, value2, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andIsCurrentNotBetween(Boolean value1, Boolean value2) {
			addCriterion("sys_confirm.is_current not between", value1, value2, "isCurrent");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("sys_confirm.create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("sys_confirm.create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("sys_confirm.create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("sys_confirm.create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("sys_confirm.create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("sys_confirm.create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("sys_confirm.create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("sys_confirm.create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("sys_confirm.create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("sys_confirm.create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("sys_confirm.create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("sys_confirm.create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andTakerIsNull() {
			addCriterion("sys_confirm.taker is null");
			return (Criteria) this;
		}

		public Criteria andTakerIsNotNull() {
			addCriterion("sys_confirm.taker is not null");
			return (Criteria) this;
		}

		public Criteria andTakerEqualTo(Boolean value) {
			addCriterion("sys_confirm.taker =", value, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerNotEqualTo(Boolean value) {
			addCriterion("sys_confirm.taker <>", value, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerGreaterThan(Boolean value) {
			addCriterion("sys_confirm.taker >", value, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerGreaterThanOrEqualTo(Boolean value) {
			addCriterion("sys_confirm.taker >=", value, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerLessThan(Boolean value) {
			addCriterion("sys_confirm.taker <", value, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerLessThanOrEqualTo(Boolean value) {
			addCriterion("sys_confirm.taker <=", value, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerIn(List<Boolean> values) {
			addCriterion("sys_confirm.taker in", values, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerNotIn(List<Boolean> values) {
			addCriterion("sys_confirm.taker not in", values, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerBetween(Boolean value1, Boolean value2) {
			addCriterion("sys_confirm.taker between", value1, value2, "taker");
			return (Criteria) this;
		}

		public Criteria andTakerNotBetween(Boolean value1, Boolean value2) {
			addCriterion("sys_confirm.taker not between", value1, value2, "taker");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("sys_confirm.order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("sys_confirm.order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(Byte value) {
			addCriterion("sys_confirm.order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(Byte value) {
			addCriterion("sys_confirm.order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(Byte value) {
			addCriterion("sys_confirm.order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(Byte value) {
			addCriterion("sys_confirm.order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<Byte> values) {
			addCriterion("sys_confirm.order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<Byte> values) {
			addCriterion("sys_confirm.order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.order_status not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andResultIsNull() {
			addCriterion("sys_confirm.result is null");
			return (Criteria) this;
		}

		public Criteria andResultIsNotNull() {
			addCriterion("sys_confirm.result is not null");
			return (Criteria) this;
		}

		public Criteria andResultEqualTo(Byte value) {
			addCriterion("sys_confirm.result =", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotEqualTo(Byte value) {
			addCriterion("sys_confirm.result <>", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThan(Byte value) {
			addCriterion("sys_confirm.result >", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.result >=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThan(Byte value) {
			addCriterion("sys_confirm.result <", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.result <=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultIn(List<Byte> values) {
			addCriterion("sys_confirm.result in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotIn(List<Byte> values) {
			addCriterion("sys_confirm.result not in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.result between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.result not between", value1, value2, "result");
			return (Criteria) this;
		}
		
		public Criteria andMoneyIsNull() {
			addCriterion("sys_confirm.money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("sys_confirm.money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Double value) {
			addCriterion("sys_confirm.money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Double value) {
			addCriterion("sys_confirm.money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Double value) {
			addCriterion("sys_confirm.money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("sys_confirm.money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Double value) {
			addCriterion("sys_confirm.money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Double value) {
			addCriterion("sys_confirm.money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Double> values) {
			addCriterion("sys_confirm.money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Double> values) {
			addCriterion("sys_confirm.money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Double value1, Double value2) {
			addCriterion("sys_confirm.money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Double value1, Double value2) {
			addCriterion("sys_confirm.money not between", value1, value2, "money");
			return (Criteria) this;
		}
		
		public Criteria andTypeIsNull() {
			addCriterion("sys_confirm.type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("sys_confirm.type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Byte value) {
			addCriterion("sys_confirm.type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Byte value) {
			addCriterion("sys_confirm.type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Byte value) {
			addCriterion("sys_confirm.type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Byte value) {
			addCriterion("sys_confirm.type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Byte> values) {
			addCriterion("sys_confirm.type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Byte> values) {
			addCriterion("sys_confirm.type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.type between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.type not between", value1, value2, "money");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_confirm
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}