package com.cishi.beans;

import java.util.Date;

public class SysConfirm {
	private String iframeFile;
	

	public String getIframeFile() {
		return iframeFile;
	}

	public void setIframeFile(String iframeFile) {
		this.iframeFile = iframeFile;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.order_id
	 * @mbggenerated
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.one_partner_id
	 * @mbggenerated
	 */
	private String onePartnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.sec_partner_id
	 * @mbggenerated
	 */
	private String secPartnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.one_partner_status
	 * @mbggenerated
	 */
	private Byte onePartnerStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.sec_partner_status
	 * @mbggenerated
	 */
	private Byte secPartnerStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.on_partner_remark
	 * @mbggenerated
	 */
	private String onPartnerRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.sec_partner_remark
	 * @mbggenerated
	 */
	private String secPartnerRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.one_partner_date
	 * @mbggenerated
	 */
	private Date onePartnerDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.sec_partner_date
	 * @mbggenerated
	 */
	private Date secPartnerDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.is_current
	 * @mbggenerated
	 */
	private Boolean isCurrent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.taker
	 * @mbggenerated
	 */
	private Boolean taker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.order_status
	 * @mbggenerated
	 */
	private Byte orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.result
	 * @mbggenerated
	 */
	private Byte result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_confirm.money
	 * @mbggenerated
	 */
	private Double money;
	
	private Byte type;
	

	public Byte getType() {
		return type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.id
	 * @return  the value of sys_confirm.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.id
	 * @param id  the value for sys_confirm.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.order_id
	 * @return  the value of sys_confirm.order_id
	 * @mbggenerated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.order_id
	 * @param orderId  the value for sys_confirm.order_id
	 * @mbggenerated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.one_partner_id
	 * @return  the value of sys_confirm.one_partner_id
	 * @mbggenerated
	 */
	public String getOnePartnerId() {
		return onePartnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.one_partner_id
	 * @param onePartnerId  the value for sys_confirm.one_partner_id
	 * @mbggenerated
	 */
	public void setOnePartnerId(String onePartnerId) {
		this.onePartnerId = onePartnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.sec_partner_id
	 * @return  the value of sys_confirm.sec_partner_id
	 * @mbggenerated
	 */
	public String getSecPartnerId() {
		return secPartnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.sec_partner_id
	 * @param secPartnerId  the value for sys_confirm.sec_partner_id
	 * @mbggenerated
	 */
	public void setSecPartnerId(String secPartnerId) {
		this.secPartnerId = secPartnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.del_flag
	 * @return  the value of sys_confirm.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.del_flag
	 * @param delFlag  the value for sys_confirm.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.one_partner_status
	 * @return  the value of sys_confirm.one_partner_status
	 * @mbggenerated
	 */
	public Byte getOnePartnerStatus() {
		return onePartnerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.one_partner_status
	 * @param onePartnerStatus  the value for sys_confirm.one_partner_status
	 * @mbggenerated
	 */
	public void setOnePartnerStatus(Byte onePartnerStatus) {
		this.onePartnerStatus = onePartnerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.sec_partner_status
	 * @return  the value of sys_confirm.sec_partner_status
	 * @mbggenerated
	 */
	public Byte getSecPartnerStatus() {
		return secPartnerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.sec_partner_status
	 * @param secPartnerStatus  the value for sys_confirm.sec_partner_status
	 * @mbggenerated
	 */
	public void setSecPartnerStatus(Byte secPartnerStatus) {
		this.secPartnerStatus = secPartnerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.on_partner_remark
	 * @return  the value of sys_confirm.on_partner_remark
	 * @mbggenerated
	 */
	public String getOnPartnerRemark() {
		return onPartnerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.on_partner_remark
	 * @param onPartnerRemark  the value for sys_confirm.on_partner_remark
	 * @mbggenerated
	 */
	public void setOnPartnerRemark(String onPartnerRemark) {
		this.onPartnerRemark = onPartnerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.sec_partner_remark
	 * @return  the value of sys_confirm.sec_partner_remark
	 * @mbggenerated
	 */
	public String getSecPartnerRemark() {
		return secPartnerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.sec_partner_remark
	 * @param secPartnerRemark  the value for sys_confirm.sec_partner_remark
	 * @mbggenerated
	 */
	public void setSecPartnerRemark(String secPartnerRemark) {
		this.secPartnerRemark = secPartnerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.one_partner_date
	 * @return  the value of sys_confirm.one_partner_date
	 * @mbggenerated
	 */
	public Date getOnePartnerDate() {
		return onePartnerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.one_partner_date
	 * @param onePartnerDate  the value for sys_confirm.one_partner_date
	 * @mbggenerated
	 */
	public void setOnePartnerDate(Date onePartnerDate) {
		this.onePartnerDate = onePartnerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.sec_partner_date
	 * @return  the value of sys_confirm.sec_partner_date
	 * @mbggenerated
	 */
	public Date getSecPartnerDate() {
		return secPartnerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.sec_partner_date
	 * @param secPartnerDate  the value for sys_confirm.sec_partner_date
	 * @mbggenerated
	 */
	public void setSecPartnerDate(Date secPartnerDate) {
		this.secPartnerDate = secPartnerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.is_current
	 * @return  the value of sys_confirm.is_current
	 * @mbggenerated
	 */
	public Boolean getIsCurrent() {
		return isCurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.is_current
	 * @param isCurrent  the value for sys_confirm.is_current
	 * @mbggenerated
	 */
	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.create_date
	 * @return  the value of sys_confirm.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.create_date
	 * @param createDate  the value for sys_confirm.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.taker
	 * @return  the value of sys_confirm.taker
	 * @mbggenerated
	 */
	public Boolean getTaker() {
		return taker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.taker
	 * @param taker  the value for sys_confirm.taker
	 * @mbggenerated
	 */
	public void setTaker(Boolean taker) {
		this.taker = taker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.order_status
	 * @return  the value of sys_confirm.order_status
	 * @mbggenerated
	 */
	public Byte getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.order_status
	 * @param orderStatus  the value for sys_confirm.order_status
	 * @mbggenerated
	 */
	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.result
	 * @return  the value of sys_confirm.result
	 * @mbggenerated
	 */
	public Byte getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.result
	 * @param result  the value for sys_confirm.result
	 * @mbggenerated
	 */
	public void setResult(Byte result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_confirm.money
	 * @return  the value of sys_confirm.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_confirm.money
	 * @param money  the value for sys_confirm.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}
}