package com.cishi.beans;

import java.util.ArrayList;
import java.util.List;

public class SysCompanyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_company
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_company
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_company
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public SysCompanyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_company
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("sys_confirm.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("sys_confirm.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("sys_confirm.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("sys_confirm.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("sys_confirm.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("sys_confirm.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("sys_confirm.id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("sys_confirm.id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("sys_confirm.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("sys_confirm.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("sys_confirm.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("sys_confirm.company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("sys_confirm.company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("sys_confirm.company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("sys_confirm.company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("sys_confirm.company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("sys_confirm.company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("sys_confirm.company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("sys_confirm.company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("sys_confirm.company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("sys_confirm.company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("sys_confirm.company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("sys_confirm.login_name is null");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("sys_confirm.login_name is not null");
			return (Criteria) this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("sys_confirm.login_name =", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("sys_confirm.login_name <>", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("sys_confirm.login_name >", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.login_name >=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("sys_confirm.login_name <", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.login_name <=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("sys_confirm.login_name like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("sys_confirm.login_name not like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("sys_confirm.login_name in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("sys_confirm.login_name not in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("sys_confirm.login_name between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.login_name not between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNull() {
			addCriterion("sys_confirm.phone_number is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNotNull() {
			addCriterion("sys_confirm.phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberEqualTo(String value) {
			addCriterion("sys_confirm.phone_number =", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotEqualTo(String value) {
			addCriterion("sys_confirm.phone_number <>", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThan(String value) {
			addCriterion("sys_confirm.phone_number >", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.phone_number >=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThan(String value) {
			addCriterion("sys_confirm.phone_number <", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.phone_number <=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLike(String value) {
			addCriterion("sys_confirm.phone_number like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotLike(String value) {
			addCriterion("sys_confirm.phone_number not like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIn(List<String> values) {
			addCriterion("sys_confirm.phone_number in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotIn(List<String> values) {
			addCriterion("sys_confirm.phone_number not in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberBetween(String value1, String value2) {
			addCriterion("sys_confirm.phone_number between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("sys_confirm.phone_number not between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("sys_confirm.del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("sys_confirm.del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("sys_confirm.del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("sys_confirm.del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("sys_confirm.del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("sys_confirm.del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("sys_confirm.STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("sys_confirm.STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("sys_confirm.STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("sys_confirm.STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("sys_confirm.STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("sys_confirm.STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("sys_confirm.STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("sys_confirm.STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("sys_confirm.STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("sys_confirm.STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andInfoObli1IsNull() {
			addCriterion("sys_confirm.info_obli_1 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli1IsNotNull() {
			addCriterion("sys_confirm.info_obli_1 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli1EqualTo(String value) {
			addCriterion("sys_confirm.info_obli_1 =", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_1 <>", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1GreaterThan(String value) {
			addCriterion("sys_confirm.info_obli_1 >", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1GreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_1 >=", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1LessThan(String value) {
			addCriterion("sys_confirm.info_obli_1 <", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1LessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_1 <=", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1Like(String value) {
			addCriterion("sys_confirm.info_obli_1 like", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotLike(String value) {
			addCriterion("sys_confirm.info_obli_1 not like", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1In(List<String> values) {
			addCriterion("sys_confirm.info_obli_1 in", values, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotIn(List<String> values) {
			addCriterion("sys_confirm.info_obli_1 not in", values, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1Between(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_1 between", value1, value2, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotBetween(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_1 not between", value1, value2, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli2IsNull() {
			addCriterion("sys_confirm.info_obli_2 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli2IsNotNull() {
			addCriterion("sys_confirm.info_obli_2 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli2EqualTo(String value) {
			addCriterion("sys_confirm.info_obli_2 =", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_2 <>", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2GreaterThan(String value) {
			addCriterion("sys_confirm.info_obli_2 >", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2GreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_2 >=", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2LessThan(String value) {
			addCriterion("sys_confirm.info_obli_2 <", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2LessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_2 <=", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2Like(String value) {
			addCriterion("sys_confirm.info_obli_2 like", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotLike(String value) {
			addCriterion("sys_confirm.info_obli_2 not like", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2In(List<String> values) {
			addCriterion("sys_confirm.info_obli_2 in", values, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotIn(List<String> values) {
			addCriterion("sys_confirm.info_obli_2 not in", values, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2Between(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_2 between", value1, value2, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotBetween(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_2 not between", value1, value2, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli3IsNull() {
			addCriterion("sys_confirm.info_obli_3 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli3IsNotNull() {
			addCriterion("sys_confirm.info_obli_3 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli3EqualTo(String value) {
			addCriterion("sys_confirm.info_obli_3 =", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_3 <>", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3GreaterThan(String value) {
			addCriterion("sys_confirm.info_obli_3 >", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3GreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_3 >=", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3LessThan(String value) {
			addCriterion("sys_confirm.info_obli_3 <", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3LessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_3 <=", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3Like(String value) {
			addCriterion("sys_confirm.info_obli_3 like", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotLike(String value) {
			addCriterion("sys_confirm.info_obli_3 not like", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3In(List<String> values) {
			addCriterion("sys_confirm.info_obli_3 in", values, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotIn(List<String> values) {
			addCriterion("sys_confirm.info_obli_3 not in", values, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3Between(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_3 between", value1, value2, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotBetween(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_3 not between", value1, value2, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli4IsNull() {
			addCriterion("sys_confirm.info_obli_4 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli4IsNotNull() {
			addCriterion("sys_confirm.info_obli_4 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli4EqualTo(String value) {
			addCriterion("sys_confirm.info_obli_4 =", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_4 <>", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4GreaterThan(String value) {
			addCriterion("sys_confirm.info_obli_4 >", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4GreaterThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_4 >=", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4LessThan(String value) {
			addCriterion("sys_confirm.info_obli_4 <", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4LessThanOrEqualTo(String value) {
			addCriterion("sys_confirm.info_obli_4 <=", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4Like(String value) {
			addCriterion("sys_confirm.info_obli_4 like", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotLike(String value) {
			addCriterion("sys_confirm.info_obli_4 not like", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4In(List<String> values) {
			addCriterion("sys_confirm.info_obli_4 in", values, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotIn(List<String> values) {
			addCriterion("sys_confirm.info_obli_4 not in", values, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4Between(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_4 between", value1, value2, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotBetween(String value1, String value2) {
			addCriterion("sys_confirm.info_obli_4 not between", value1, value2, "infoObli4");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_company
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}