package com.cishi.beans;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class SysFieldExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_field
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_field
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_field
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public SysFieldExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_field
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFieldNameIsNull() {
			addCriterion("field_name is null");
			return (Criteria) this;
		}

		public Criteria andFieldNameIsNotNull() {
			addCriterion("field_name is not null");
			return (Criteria) this;
		}

		public Criteria andFieldNameEqualTo(String value) {
			addCriterion("field_name =", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotEqualTo(String value) {
			addCriterion("field_name <>", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameGreaterThan(String value) {
			addCriterion("field_name >", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameGreaterThanOrEqualTo(String value) {
			addCriterion("field_name >=", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLessThan(String value) {
			addCriterion("field_name <", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLessThanOrEqualTo(String value) {
			addCriterion("field_name <=", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLike(String value) {
			addCriterion("field_name like", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotLike(String value) {
			addCriterion("field_name not like", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameIn(List<String> values) {
			addCriterion("field_name in", values, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotIn(List<String> values) {
			addCriterion("field_name not in", values, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameBetween(String value1, String value2) {
			addCriterion("field_name between", value1, value2, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotBetween(String value1, String value2) {
			addCriterion("field_name not between", value1, value2, "fieldName");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andInfoObli1IsNull() {
			addCriterion("info_obli_1 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli1IsNotNull() {
			addCriterion("info_obli_1 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli1EqualTo(String value) {
			addCriterion("info_obli_1 =", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotEqualTo(String value) {
			addCriterion("info_obli_1 <>", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1GreaterThan(String value) {
			addCriterion("info_obli_1 >", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1GreaterThanOrEqualTo(String value) {
			addCriterion("info_obli_1 >=", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1LessThan(String value) {
			addCriterion("info_obli_1 <", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1LessThanOrEqualTo(String value) {
			addCriterion("info_obli_1 <=", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1Like(String value) {
			addCriterion("info_obli_1 like", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotLike(String value) {
			addCriterion("info_obli_1 not like", value, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1In(List<String> values) {
			addCriterion("info_obli_1 in", values, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotIn(List<String> values) {
			addCriterion("info_obli_1 not in", values, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1Between(String value1, String value2) {
			addCriterion("info_obli_1 between", value1, value2, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli1NotBetween(String value1, String value2) {
			addCriterion("info_obli_1 not between", value1, value2, "infoObli1");
			return (Criteria) this;
		}

		public Criteria andInfoObli2IsNull() {
			addCriterion("info_obli_2 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli2IsNotNull() {
			addCriterion("info_obli_2 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli2EqualTo(String value) {
			addCriterion("info_obli_2 =", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotEqualTo(String value) {
			addCriterion("info_obli_2 <>", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2GreaterThan(String value) {
			addCriterion("info_obli_2 >", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2GreaterThanOrEqualTo(String value) {
			addCriterion("info_obli_2 >=", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2LessThan(String value) {
			addCriterion("info_obli_2 <", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2LessThanOrEqualTo(String value) {
			addCriterion("info_obli_2 <=", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2Like(String value) {
			addCriterion("info_obli_2 like", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotLike(String value) {
			addCriterion("info_obli_2 not like", value, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2In(List<String> values) {
			addCriterion("info_obli_2 in", values, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotIn(List<String> values) {
			addCriterion("info_obli_2 not in", values, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2Between(String value1, String value2) {
			addCriterion("info_obli_2 between", value1, value2, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli2NotBetween(String value1, String value2) {
			addCriterion("info_obli_2 not between", value1, value2, "infoObli2");
			return (Criteria) this;
		}

		public Criteria andInfoObli3IsNull() {
			addCriterion("info_obli_3 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli3IsNotNull() {
			addCriterion("info_obli_3 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli3EqualTo(String value) {
			addCriterion("info_obli_3 =", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotEqualTo(String value) {
			addCriterion("info_obli_3 <>", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3GreaterThan(String value) {
			addCriterion("info_obli_3 >", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3GreaterThanOrEqualTo(String value) {
			addCriterion("info_obli_3 >=", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3LessThan(String value) {
			addCriterion("info_obli_3 <", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3LessThanOrEqualTo(String value) {
			addCriterion("info_obli_3 <=", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3Like(String value) {
			addCriterion("info_obli_3 like", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotLike(String value) {
			addCriterion("info_obli_3 not like", value, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3In(List<String> values) {
			addCriterion("info_obli_3 in", values, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotIn(List<String> values) {
			addCriterion("info_obli_3 not in", values, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3Between(String value1, String value2) {
			addCriterion("info_obli_3 between", value1, value2, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli3NotBetween(String value1, String value2) {
			addCriterion("info_obli_3 not between", value1, value2, "infoObli3");
			return (Criteria) this;
		}

		public Criteria andInfoObli4IsNull() {
			addCriterion("info_obli_4 is null");
			return (Criteria) this;
		}

		public Criteria andInfoObli4IsNotNull() {
			addCriterion("info_obli_4 is not null");
			return (Criteria) this;
		}

		public Criteria andInfoObli4EqualTo(String value) {
			addCriterion("info_obli_4 =", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotEqualTo(String value) {
			addCriterion("info_obli_4 <>", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4GreaterThan(String value) {
			addCriterion("info_obli_4 >", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4GreaterThanOrEqualTo(String value) {
			addCriterion("info_obli_4 >=", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4LessThan(String value) {
			addCriterion("info_obli_4 <", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4LessThanOrEqualTo(String value) {
			addCriterion("info_obli_4 <=", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4Like(String value) {
			addCriterion("info_obli_4 like", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotLike(String value) {
			addCriterion("info_obli_4 not like", value, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4In(List<String> values) {
			addCriterion("info_obli_4 in", values, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotIn(List<String> values) {
			addCriterion("info_obli_4 not in", values, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4Between(String value1, String value2) {
			addCriterion("info_obli_4 between", value1, value2, "infoObli4");
			return (Criteria) this;
		}

		public Criteria andInfoObli4NotBetween(String value1, String value2) {
			addCriterion("info_obli_4 not between", value1, value2, "infoObli4");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_field
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_field
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}