package com.cishi.beans;

import java.util.Date;

public class SysMoneyLockHistroy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_money_lock_histroy.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_money_lock_histroy.order_id
	 * @mbggenerated
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_money_lock_histroy.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_money_lock_histroy.del_flag
	 * @mbggenerated
	 */
	private Boolean delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_money_lock_histroy.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_money_lock_histroy.type
	 * @mbggenerated
	 */
	private Byte type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_money_lock_histroy.id
	 * @return  the value of sys_money_lock_histroy.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_money_lock_histroy.id
	 * @param id  the value for sys_money_lock_histroy.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_money_lock_histroy.order_id
	 * @return  the value of sys_money_lock_histroy.order_id
	 * @mbggenerated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_money_lock_histroy.order_id
	 * @param orderId  the value for sys_money_lock_histroy.order_id
	 * @mbggenerated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_money_lock_histroy.user_id
	 * @return  the value of sys_money_lock_histroy.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_money_lock_histroy.user_id
	 * @param userId  the value for sys_money_lock_histroy.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_money_lock_histroy.del_flag
	 * @return  the value of sys_money_lock_histroy.del_flag
	 * @mbggenerated
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_money_lock_histroy.del_flag
	 * @param delFlag  the value for sys_money_lock_histroy.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_money_lock_histroy.create_date
	 * @return  the value of sys_money_lock_histroy.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_money_lock_histroy.create_date
	 * @param createDate  the value for sys_money_lock_histroy.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_money_lock_histroy.type
	 * @return  the value of sys_money_lock_histroy.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_money_lock_histroy.type
	 * @param type  the value for sys_money_lock_histroy.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}
}