package com.cishi.beans;

public class SysScore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_score.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_score.score
	 * @mbggenerated
	 */
	private Double score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_score.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_score.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_score.task_id
	 * @mbggenerated
	 */
	private String taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_score.rater_user_id
	 * @mbggenerated
	 */
	private String raterUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_score.id
	 * @return  the value of sys_score.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_score.id
	 * @param id  the value for sys_score.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_score.score
	 * @return  the value of sys_score.score
	 * @mbggenerated
	 */
	public Double getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_score.score
	 * @param score  the value for sys_score.score
	 * @mbggenerated
	 */
	public void setScore(Double score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_score.user_id
	 * @return  the value of sys_score.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_score.user_id
	 * @param userId  the value for sys_score.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_score.del_flag
	 * @return  the value of sys_score.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_score.del_flag
	 * @param delFlag  the value for sys_score.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_score.task_id
	 * @return  the value of sys_score.task_id
	 * @mbggenerated
	 */
	public String getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_score.task_id
	 * @param taskId  the value for sys_score.task_id
	 * @mbggenerated
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_score.rater_user_id
	 * @return  the value of sys_score.rater_user_id
	 * @mbggenerated
	 */
	public String getRaterUserId() {
		return raterUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_score.rater_user_id
	 * @param raterUserId  the value for sys_score.rater_user_id
	 * @mbggenerated
	 */
	public void setRaterUserId(String raterUserId) {
		this.raterUserId = raterUserId;
	}
}