package com.cishi.beans;

public class SysTradeInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.money
	 * @mbggenerated
	 */
	private Double money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.type
	 * @mbggenerated
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.del_flag
	 * @mbggenerated
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.trade_id
	 * @mbggenerated
	 */
	private String tradeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_trade_info.pay_account
	 * @mbggenerated
	 */
	private String payAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.id
	 * @return  the value of sys_trade_info.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.id
	 * @param id  the value for sys_trade_info.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.user_id
	 * @return  the value of sys_trade_info.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.user_id
	 * @param userId  the value for sys_trade_info.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.money
	 * @return  the value of sys_trade_info.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.money
	 * @param money  the value for sys_trade_info.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.type
	 * @return  the value of sys_trade_info.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.type
	 * @param type  the value for sys_trade_info.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.status
	 * @return  the value of sys_trade_info.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.status
	 * @param status  the value for sys_trade_info.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.del_flag
	 * @return  the value of sys_trade_info.del_flag
	 * @mbggenerated
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.del_flag
	 * @param delFlag  the value for sys_trade_info.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.trade_id
	 * @return  the value of sys_trade_info.trade_id
	 * @mbggenerated
	 */
	public String getTradeId() {
		return tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.trade_id
	 * @param tradeId  the value for sys_trade_info.trade_id
	 * @mbggenerated
	 */
	public void setTradeId(String tradeId) {
		this.tradeId = tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_trade_info.pay_account
	 * @return  the value of sys_trade_info.pay_account
	 * @mbggenerated
	 */
	public String getPayAccount() {
		return payAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_trade_info.pay_account
	 * @param payAccount  the value for sys_trade_info.pay_account
	 * @mbggenerated
	 */
	public void setPayAccount(String payAccount) {
		this.payAccount = payAccount;
	}
}