package com.cishi.dao;

import com.cishi.beans.OrderTask;
import com.cishi.beans.OrderTaskCollection;
import com.cishi.beans.OrderTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import com.cishi.beans.OrderTaskWithBLOBs;

public interface OrderTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int countByExample(OrderTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int deleteByExample(OrderTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int insert(OrderTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int insertSelective(OrderTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	List<OrderTaskCollection> selectByExampleWithRowbounds(OrderTaskExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	List<OrderTask> selectByExample(OrderTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	OrderTask selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") OrderTask record, @Param("example") OrderTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") OrderTask record, @Param("example") OrderTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OrderTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_task
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderTask record);

	OrderTaskCollection selectReferByPrimaryKey(@Param("id")String id,@Param("userId")String userId,@Param("confirmType")String confirmType);
	
	List<OrderTaskCollection> selectByExampleByReceiveId(OrderTaskExample example,RowBounds rowBounds);
	
	String getStartEmailByOrderId(String orderId);
}