package com.cishi.dao;

import com.cishi.beans.OrderReceive;
import com.cishi.beans.OrderReceiveExample;
import com.cishi.view.OrderReceiveView;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderReceiveMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int countByExample(OrderReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int deleteByExample(OrderReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int insert(OrderReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int insertSelective(OrderReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	List<OrderReceive> selectByExampleWithRowbounds(OrderReceiveExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	List<OrderReceive> selectByExample(OrderReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	OrderReceive selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") OrderReceive record, @Param("example") OrderReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") OrderReceive record, @Param("example") OrderReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OrderReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_receive
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderReceive record);

	List<OrderReceiveView> selectReferList(OrderReceiveExample example);
}