package com.cishi.dao;

import com.cishi.beans.SysAccountDetail;
import com.cishi.beans.SysAccountDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysAccountDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int countByExample(SysAccountDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int deleteByExample(SysAccountDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int insert(SysAccountDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int insertSelective(SysAccountDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	List<SysAccountDetail> selectByExampleWithRowbounds(SysAccountDetailExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	List<SysAccountDetail> selectByExample(SysAccountDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	SysAccountDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SysAccountDetail record,
			@Param("example") SysAccountDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SysAccountDetail record, @Param("example") SysAccountDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysAccountDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_account_detail
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysAccountDetail record);
}