package com.cishi.dao;

import com.cishi.beans.SysConfirm;
import com.cishi.beans.SysConfirmExample;
import com.cishi.collection.SysConfirmCollection;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysConfirmMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int countByExample(SysConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int deleteByExample(SysConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int insert(SysConfirm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int insertSelective(SysConfirm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	List<SysConfirm> selectByExampleWithRowbounds(SysConfirmExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	List<SysConfirmCollection> selectByExample(SysConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	SysConfirm selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SysConfirm record, @Param("example") SysConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SysConfirm record, @Param("example") SysConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysConfirm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_confirm
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysConfirm record);
	
	String getEmailByConfirmId(String confirmId);
}