package com.cishi.dao;

import com.cishi.beans.SysCompany;
import com.cishi.beans.SysCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int countByExample(SysCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int deleteByExample(SysCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int insert(SysCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int insertSelective(SysCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	List<SysCompany> selectByExampleWithRowbounds(SysCompanyExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	List<SysCompany> selectByExample(SysCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	SysCompany selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SysCompany record, @Param("example") SysCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SysCompany record, @Param("example") SysCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysCompany record);
}