package com.cishi.dao;

import com.cishi.beans.SysMoneyLockHistroy;
import com.cishi.beans.SysMoneyLockHistroyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysMoneyLockHistroyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int countByExample(SysMoneyLockHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int deleteByExample(SysMoneyLockHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int insert(SysMoneyLockHistroy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int insertSelective(SysMoneyLockHistroy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	List<SysMoneyLockHistroy> selectByExampleWithRowbounds(SysMoneyLockHistroyExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	List<SysMoneyLockHistroy> selectByExample(SysMoneyLockHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	SysMoneyLockHistroy selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SysMoneyLockHistroy record,
			@Param("example") SysMoneyLockHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SysMoneyLockHistroy record,
			@Param("example") SysMoneyLockHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysMoneyLockHistroy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_money_lock_histroy
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysMoneyLockHistroy record);
}