package com.cishi.dao;

import com.cishi.beans.SysTradeInfo;
import com.cishi.beans.SysTradeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysTradeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int countByExample(SysTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int deleteByExample(SysTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int insert(SysTradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int insertSelective(SysTradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	List<SysTradeInfo> selectByExampleWithRowbounds(SysTradeInfoExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	List<SysTradeInfo> selectByExample(SysTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	SysTradeInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SysTradeInfo record, @Param("example") SysTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SysTradeInfo record, @Param("example") SysTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysTradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_trade_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysTradeInfo record);
}